version: '3.3'

volumes:
  postgres_data:
      driver: local

services:
  db:
    build: ./db
    image: proof_db        
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/proof:rw
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proof

  app:
    build: ./app
    image: proof
    ports:
      - "5000:5000"
    depends_on:
      - db
  

