version: '3.3'

volumes:
  postgres_data:
      driver: local

services:
  db:
    build: ./db
    image: proof_db        
    restart: always
    ports: 
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql:rw
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proof

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: ./app
    image: artiegold_proof
    ports:
      - 5001:5000
    depends_on:
      - db
    links:
      - db:db

